services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "5173:5173"
    networks:
      - transcendence-net
    environment:
      - NODE_ENV=development
      - VITE_APP_TITLE=Transcendence
    volumes:
      - ./src:/usr/src/app/src
      - ./public:/usr/src/app/public
      - /usr/src/app/node_modules
    command: npm run dev -- --host 0.0.0.0 --port 5173
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:5173"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  transcendence-net:
    driver: bridge
